language: node_js
node_js:
  - 14.15.0

install:
  - npm install

dist: xenial

os: linux

script:
  - npm ci
  - npm run test

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: API_KEY
  app: mighty-everglades-35186