language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run test

deploy:
  provider: heroku
  api_key:
    secure: $GITHUB_TOKEN
  app: mighty-everglades-35186
  on:
    repo: mdirshaddev/UrlShortener