language: node_js
node_js:
  - 14

install:
  - npm install

dist: xenial

os: linux

script:
  - npm ci
  - npm run test
  - npm run start

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: 2204b876-94cb-471f-9fc5-ee2ae0c4f6ff
  app: mighty-everglades-35186